# Generated by Django 3.2.8 on 2021-10-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('abbreviation', models.CharField(max_length=7, unique=True)),
                ('description', models.CharField(max_length=3000)),
                ('icon', models.CharField(max_length=27)),
            ],
            options={
                'db_table': 'coins',
            },
        ),
    ]
