apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-coin-prices
  namespace: bitbuyer
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-coin-prices
              image: user632716/scripts:latest
              command: ["/usr/local/bin/python"]
              args: ["/app/scripts/update_current_prices.py"]
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-auth
                      key: POSTGRES_PASSWORD

                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-auth
                      key: POSTGRES_USER

                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_HOST

                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_PORT

          restartPolicy: OnFailure
