---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: bitbuyer
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:14.0
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data/
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: POSTGRES_PASSWORD

            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PGDATA

      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc
