apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: bitbuyer
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pgpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret-key
  namespace: bitbuyer
type: Opaque
stringData:
  SECRET_KEY: dev
