---
apiVersion: v1
kind: Service
metadata:
  name: back-internal
  namespace: bitbuyer
spec:
  type: ClusterIP
  selector:
    app: bitbuyer-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: standard
